[pyprland]
plugins = ["scratchpads"]

[scratchpads.pwvucontrol]
animation = "fromTop"
command = "pwvucontrol"
class = "pwvucontrol"
size = "50% 80%"

[scratchpads.term]
command = "ghostty"
animation = "fromTop"
class = "com.example.scratchpad"
# size = "75% 60%"
