# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$kubernetes\
$time \
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[time]
disabled = false
time_format = "%r"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = 'last command: [$duration](bold yellow)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
'kubernetes-admin-homelab-k8s@homelab-k8s' = 'homelab-k8s'
'gke_(?P<env>tally-(?:stage|live))_.*' = 'gke-$env'

# ---

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[gcloud]
symbol = "󱇶 "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "bold yellow"

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "


[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
# Only use the `python3` binary to get the version.
python_binary = "python3"

[ruby]
symbol = " "

[rust]
symbol = " "
