[colors]
ansi = [
  "#3f4451",
  "#ed8796",
  "#a6da95",
  "#d19a66",
  "#61afef",
  "#c678dd",
  "#56b6c2",
  "#e6e6e6",
]
brights = [
  "#4f5666",
  "#ff7b86",
  "#b1e18b",
  "#efb074",
  "#67cdff",
  "#e48bff",
  "#63d4e0",
  "#ffffff",
]
background = "#282c34"
foreground = "#abb2bf"
cursor_bg = "#a6da95"
compose_cursor = "#f0c6c6"
cursor_border = "#f4dbd6"
cursor_fg = "#181926"
scrollbar_thumb = "#5b6078"
selection_bg = "#5b6078"
selection_fg = "#cad3f5"
split = "#6e738d"
visual_bell = "#363a4f"

[metadata]
aliases = []
author = "Peter"
name = "Dark One Nuanced Custom"
